### ISSUE TITLE
replace backdrop-filter blur with svg instead

### ISSUE THREAD

**Issue by omar2205** [leerob/leerob.io#268]
backdrop-filter blur doesn't look good compared to SVG based blur
![](https://i.imgur.com/DzRFiBi.png)
vs SVG based
![](https://i.imgur.com/rFpXT2V.png)
```css
nav {
  background-color: rgba(255,255,255,.72);
  backdrop-filter: saturate(180%) url(#sharpBlur);
}
```
```html
<svg class="svg-blur" style="display: none;">
  <filter id="sharpBlur">
    <feGaussianBlur stdDeviation="20"></feGaussianBlur>
    <feColorMatrix type="matrix" values="1 0 0 0 0, 0 1 0 0 0, 0 0 1 0 0, 0 0 0 9 0"></feColorMatrix>
    <feComposite in2="SourceGraphic" operator="in"></feComposite>
  </filter>
</svg>
```
